version: '3.4'
services:
  ffmpeg-watch:
    container_name: ffmpeg-watch
    image: ghcr.io/behappiness/ffmpeg-watchfolder:latest
    restart: always
    environment:
      ENCODER: libx264
      PRESET: veryfast
      CRF: 28
      EXTENSION: mp4
      FPS: 50
      THREADS: 4
      DISABLE_AUDIO: "false"
      NAME: "50fps"
      DELETE_ORIGINAL: "false"
    volumes:
      - './watch:/watch'
      - './storage:/storage'
      - './output:/output'
      - './temp:/temp'
