version: '3.4'
services:
  ffmpeg-watch:
    container_name: ffmpeg-watch
    build: .
    restart: always
    environment:
      ENCODER: libx264
      PRESET: veryfast
      CRF: 28
      EXTENSION: mp4
      FPS: 50
      THREADS: 2
      DISABLE_AUDIO: "false"
      NAME: "${FPS}fps"
      DELETE_ORIGINAL: "false"
    volumes:
      - '/watch:/watch'
      - '/storage:/storage'
      - '/output:/output'
      - '/temp:/temp'
